#include <iostream>

#include "TheFiveElements.h"

using namespace std;

int main() {
    unsigned int numCases(0);  // number of input cases
    cin >> numCases;
    TheFiveElements firstElement, secondElement;
    for (unsigned int i = 0; i < numCases; ++i) {
        //1 2
        cin >> firstElement >> secondElement;                      // overloaded >> operator
        cout << firstElement++ << " " << secondElement-- << endl;  // overloaded <<, ++, -- operators
        cout << ++firstElement << " " << --secondElement << endl;  // overloaded <<, ++, -- operators
        /*** Overloaded relation operators ***/
        if (firstElement > secondElement)
            cout << firstElement << " generates " << secondElement << "." << endl;
        else if (secondElement > firstElement)
            cout << firstElement << " is generated by " << secondElement << "." << endl;
        else if (firstElement < secondElement)
            cout << firstElement << " overcomes " << secondElement << "." << endl;
        else if (secondElement < firstElement)
            cout << firstElement << " is overcome by " << secondElement << "." << endl;
        else
            cout << firstElement << " equals to " << secondElement << "." << endl;
        cout << endl;
    }

    return 0;
}
